version: "3"
services:

  frontend:
    container_name: frontend
    build: 
      context: .
    restart: always
    networks:
      project-network:
        ipv4_address: 192.168.41.3
    ports:
      - "5173:5173"
      - "4000:4000"
    volumes:
      - ./src:/app/src

networks:
  project-network:
    ipam:
      driver: default
      config:
        - subnet: 192.168.41.0/24
